[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.0.0"
fibonacci-lib = { path = "../lib" }
serde = "1.0.219"
sha2 = "0.10.9"
